namespace EmployeeControl.Application.Features.CompanyTasks.Queries.GetEmployeesUnassignedTaskByCompanyTaskId;

public record GetEmployeesUnassignedTaskByCompanyTaskIdResponse(string Id, string Name);
