default:
  interruptible: true

stages:
  - build
  - tests
  - deploy

variables:
  CSPROJ_PATH: 'src/WebApi/WebApi.csproj'
  NPM_DIST: 'compose/postman'

build-npm:
  image: node:16
  stage: build
  script:
    - cd $NPM_ROOT
    - npm install newman -g
    - newman run ./Employee\ Control.postman_collection.json --insecure
  artifacts:
    paths:
      - $NPM_DIST/
    expire_in: 20 minutes

build:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script:
    - 'dotnet build $CSPROJ_PATH'

tests:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: tests
  script:
    - 'dotnet test $CSPROJ_PATH'

deploy:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: deploy
  script:
    - 'dotnet publish $CSPROJ_PATH'
