namespace EmployeeControl.Application.Features.Departments.Queries.GetEmployeesUnassignedDepartmentByDepartmentId;

public record GetEmployeesUnassignedDepartmentByDepartmentIdResponse(string Id, string Name);
