namespace EmployeeControl.Application.Features.Departments.Queries.GetEmployeesUnassignedDepartmentByDepartmentId;

public record GetEmployeesUnassignedDepartmentByDepartmentIdResponse(Guid Id, string Name);
